version: "3"
services:
  devsql:
    build: ./mysql/
    image: devsql
    container_name: devsql
    ports:
      - "3306:3306"
    env_file:
      - ./mysql/mysql.env
    tty: true
  app:
    build: ./app/
    image: app
    container_name: app
    ports:
      - "80:80"
    volumes:
      - ~/Netsertive/Repo:/var/www
    env_file:
      - ./app/app.env
    depends_on:
      - devsql
    tty: true