version: "3"
services:
#  mysql-local:
#    build: ./mysql/
#    image: mysql-local
#    command: service mysqld start
#    ports:
#      - "3306:3306"
#    env_file:
#      - ./mysql/mysql.env
  app:
    build: ./app/
    image: app
    ports:
      - "80:80"
    volumes:
      - type: bind
          source: ~/Netsertive/Repo
          target: /var/www
    env_file:
      - ./app/app.env
#    depends_on:
#      - mysql-local